import type { Section } from './tasks'

/* Station 1 · The Sorting Yard - three parts, each a bit harder than the last.

   Every wrong label here is a near-miss: it looks close, so you have to think
   about why it is wrong instead of just spotting something silly.

   Part 1 - fix the label.  Part 2 - check the label, then sort.
   Part 3 - clean up the examples. */

export const STATION_1_SECTIONS: Section[] = [
  {
    id: '1-0',
    title: 'Fix the wrong labels',
    blurb: 'Every tag here looks close, but each one is wrong.',
    difficulty: 'Warm-up',
    tasks: [
      {
        kind: 'fixLabel',
        id: 'f1',
        emoji: '🐝',
        badLabel: 'a wasp',
        question: 'This was tagged “a wasp”. Look closely. What is it really?',
        options: ['A wasp', 'A bee', 'A fly', 'A butterfly'],
        answer: 'A bee',
        why: 'It is fuzzy and round, not smooth and thin. That makes it a bee.',
      },
      {
        kind: 'fixLabel',
        id: 'f2',
        emoji: '🦇',
        badLabel: 'a small bird',
        question: 'Someone tagged this “a small bird” because it flies. What is it?',
        options: ['A small bird', 'A bat', 'A mouse', 'An owl'],
        answer: 'A bat',
        why: 'It flies, but it has fur and feeds its young milk. It is a bat.',
      },
      {
        kind: 'fixLabel',
        id: 'f3',
        emoji: '🍄',
        badLabel: 'a plant',
        question: 'It grows in the ground, so it was tagged “a plant”. What is it?',
        options: ['A plant', 'A mushroom', 'A flower', 'A moss'],
        answer: 'A mushroom',
        why: 'No leaves, and it does not make its own food. It is a fungus.',
      },
      {
        kind: 'fixLabel',
        id: 'f4',
        emoji: '🍋',
        badLabel: 'an orange',
        question: 'This was tagged “an orange”. What is it really?',
        options: ['An orange', 'A lemon', 'A pear', 'A grapefruit'],
        answer: 'A lemon',
        why: 'It is round citrus, but the colour and pointed ends give it away.',
      },
      {
        kind: 'fixLabel',
        id: 'f5',
        emoji: '📣',
        badLabel: 'a proven fact',
        question: 'A shout got logged as “a proven fact”. What is it really?',
        options: ['A proven fact', 'A kind question', 'A loud order with no proof', 'A helpful tip'],
        answer: 'A loud order with no proof',
        why: 'Saying it loudly does not make it true. There is no proof here.',
      },
    ],
  },
  {
    id: '1-1',
    title: 'Check the label, then sort',
    blurb: 'Some tags are honest, some are lies. Sort each one.',
    difficulty: 'Tricky',
    tasks: [
      {
        kind: 'sortCrate',
        id: 's1',
        emoji: '🍎',
        label: 'food',
        question: 'The tag says “food”. Where does the apple really go?',
        crates: ['Food', 'Tools'],
        correctCrate: 0,
        why: 'That tag was right. An apple is food.',
      },
      {
        kind: 'sortCrate',
        id: 's2',
        emoji: '🐳',
        label: 'a fish',
        question: 'The tag says “a fish”. Where does the whale really go?',
        crates: ['Fish', 'Mammals'],
        correctCrate: 1,
        why: 'It swims, but it breathes air and feeds its young milk. A mammal.',
      },
      {
        kind: 'sortCrate',
        id: 's3',
        emoji: '🐶',
        label: 'a plant',
        question: 'The tag says “a plant”. Where does the dog really go?',
        crates: ['Living things', 'Not alive'],
        correctCrate: 0,
        why: 'A dog eats, grows and breathes. It is alive.',
      },
      {
        kind: 'sortCrate',
        id: 's4',
        emoji: '🍅',
        label: 'a vegetable',
        question: 'The tag says “a vegetable”. Where does the tomato really go?',
        crates: ['Vegetables', 'Fruits'],
        correctCrate: 1,
        why: 'It grows from a flower and holds seeds, so it is a fruit.',
      },
      {
        kind: 'sortCrate',
        id: 's5',
        emoji: '🌙',
        label: 'a place you can visit',
        question: 'The tag says “a place you can visit”. Where does the moon really go?',
        crates: ['On Earth', 'Out in space'],
        correctCrate: 1,
        why: 'You cannot get there by bus. A confident tag can still be wrong.',
      },
    ],
  },
  {
    id: '1-2',
    title: 'Clean up the examples',
    blurb: 'Some examples do not belong. Tick every one that is out of place.',
    difficulty: 'Expert',
    tasks: [
      {
        kind: 'cleanSet',
        id: 'c1',
        label: 'Safe to share online',
        options: [
          { emoji: '🖼️', name: 'a travel photo' },
          { emoji: '🎨', name: 'your own artwork' },
          { emoji: '🍪', name: 'a public recipe link' },
          { emoji: '📞', name: "a parent's phone number" },
          { emoji: '🔑', name: 'your account password' },
        ],
        oddOnes: [3, 4],
        why: 'Phone numbers and passwords are private. Never share them.',
      },
      {
        kind: 'cleanSet',
        id: 'c2',
        label: 'Living things',
        options: [
          { emoji: '🌳', name: 'an oak tree' },
          { emoji: '🐝', name: 'a honeybee' },
          { emoji: '🌻', name: 'a sunflower' },
          { emoji: '🪨', name: 'a granite rock' },
          { emoji: '💧', name: 'a water droplet' },
        ],
        oddOnes: [3, 4],
        why: 'Living things grow and breathe. Rock and water do not.',
      },
      {
        kind: 'cleanSet',
        id: 'c3',
        label: 'Perfectly round',
        options: [
          { emoji: '⚽', name: 'a rubber ball' },
          { emoji: '🌕', name: 'the moon' },
          { emoji: '🍊', name: 'an orange' },
          { emoji: '🥚', name: 'an egg' },
          { emoji: '🥕', name: 'a carrot' },
        ],
        oddOnes: [3, 4],
        why: 'An egg is oval and a carrot is tapered. Neither is round.',
      },
      {
        kind: 'fixLabel',
        id: 'f6',
        emoji: '🦔',
        badLabel: 'a hairbrush',
        question: 'Tricky one. The tag says “a hairbrush”. What is it?',
        options: ['A hairbrush', 'A hedgehog', 'A pinecone', 'A cactus'],
        answer: 'A hedgehog',
        why: 'It only looks like one. Look twice before you label a picture.',
      },
    ],
  },
]
