import type { Section } from './tasks'

/* Station 1 · The Sorting Yard — three parts, each harder than the last.

   Part 1 leans on looking carefully at the picture.
   Part 2 adds labels that are sometimes honest and sometimes lies.
   Part 3 asks for several answers at once, with near-miss pictures. */

export const STATION_1_SECTIONS: Section[] = [
  {
    id: '1-0',
    title: 'Fix the wrong label',
    blurb: 'Every picture here was mislabelled. Pick the label that is actually true.',
    difficulty: 'Warm-up',
    tasks: [
      {
        kind: 'fixLabel',
        id: 'f1',
        emoji: '👾',
        badLabel: 'a sweet cupcake',
        question: 'Echo filed this picture under “a sweet cupcake”. Which label is true?',
        options: ['A sweet cupcake', 'A spiky monster', 'A loaf of bread', 'A family photo'],
        answer: 'A spiky monster',
        why: 'It is spiky and snappy, not sweet. A wrong label teaches Bolt the wrong thing.',
      },
      {
        kind: 'fixLabel',
        id: 'f2',
        emoji: '🐱',
        badLabel: 'a flying machine',
        question: 'A rumour renamed this one “a flying machine”. Which label is true?',
        options: ['A flying machine', 'A cat', 'A loudspeaker', 'A broom'],
        answer: 'A cat',
        why: 'Cats purr and nap — they do not fly. A rumour is not a fact.',
      },
      {
        kind: 'fixLabel',
        id: 'f3',
        emoji: '☂️',
        badLabel: 'a tasty snack',
        question: 'This was labelled “a tasty snack”. Which label is true?',
        options: ['A tasty snack', 'An umbrella', 'A swimming pool', 'A balloon'],
        answer: 'An umbrella',
        why: 'It keeps you dry in the rain. You cannot eat it — the label was just silly.',
      },
      {
        kind: 'fixLabel',
        id: 'f4',
        emoji: '🍋',
        badLabel: 'an orange',
        question: 'Someone called this picture “an orange”. Which label is true?',
        options: ['An orange', 'A lemon', 'A pear', 'A beach ball'],
        answer: 'A lemon',
        why: 'Look at the shape and the pointed ends. A lemon is not an orange — close is not the same.',
      },
      {
        kind: 'fixLabel',
        id: 'f5',
        emoji: '📣',
        badLabel: 'a clear instruction',
        question: 'Someone shouted “DO IT NOW!!” at Bolt. Which label is honest?',
        options: [
          'A clear instruction',
          'A kind question',
          'A vague, shouted order',
          'A helpful tip',
        ],
        answer: 'A vague, shouted order',
        why: 'It never says what to do or how. Clear instructions explain the whole job.',
      },
    ],
  },
  {
    id: '1-1',
    title: 'Check the label, then sort',
    blurb:
      'Some of these labels are true and some are lies. Look at the picture, then send it to the right crate.',
    difficulty: 'Tricky',
    tasks: [
      {
        kind: 'sortCrate',
        id: 's1',
        emoji: '🍎',
        label: 'food',
        question: 'Which crate does the apple really belong in?',
        crates: ['Food', 'Tools'],
        correctCrate: 0,
        why: 'That label was right. An apple is food — good labels are worth keeping.',
      },
      {
        kind: 'sortCrate',
        id: 's2',
        emoji: '🔧',
        label: 'food',
        question: 'The label says “food”. Which crate does the spanner really belong in?',
        crates: ['Food', 'Tools'],
        correctCrate: 1,
        why: 'The label said “food”, but a spanner is a tool. Check the picture, not the label!',
      },
      {
        kind: 'sortCrate',
        id: 's3',
        emoji: '🐶',
        label: 'a plant',
        question: 'The label says “a plant”. Which crate does the dog really belong in?',
        crates: ['Living things', 'Not alive'],
        correctCrate: 0,
        why: 'A dog eats, grows and breathes — it is a living thing, whatever the label says.',
      },
      {
        kind: 'sortCrate',
        id: 's4',
        emoji: '🎡',
        label: 'a giant fan',
        question: 'The label says “a giant fan”. Which crate does the big wheel really belong in?',
        crates: ['Has wheels', 'No wheels'],
        correctCrate: 0,
        why: 'It only looks like a fan. A big wheel is a wheel, so the label was wrong.',
      },
      {
        kind: 'sortCrate',
        id: 's5',
        emoji: '🌙',
        label: 'somewhere you can visit',
        question: 'The label says “somewhere you can visit”. Which crate does the moon belong in?',
        crates: ['On Earth', 'Out in space'],
        correctCrate: 1,
        why: 'You cannot catch a bus to the moon! It is out in space.',
      },
    ],
  },
  {
    id: '1-2',
    title: 'Clean the sets',
    blurb:
      'These example sets are messy. Tap every example that does not belong — there may be more than one.',
    difficulty: 'Expert',
    tasks: [
      {
        kind: 'cleanSet',
        id: 'c1',
        label: 'Safe to share online',
        options: [
          { emoji: '🖼️', name: 'a holiday photo' },
          { emoji: '🎨', name: 'your own drawing' },
          { emoji: '🍪', name: 'a cookie recipe' },
          { emoji: '📞', name: "Mum's phone number" },
          { emoji: '🔑', name: 'your password' },
        ],
        oddOnes: [3, 4],
        why: 'Phone numbers and passwords are private. Some things should never be shared.',
      },
      {
        kind: 'cleanSet',
        id: 'c2',
        label: 'Things that are alive',
        options: [
          { emoji: '🌳', name: 'a tree' },
          { emoji: '🐝', name: 'a bee' },
          { emoji: '🌻', name: 'a sunflower' },
          { emoji: '🪨', name: 'a rock' },
          { emoji: '💧', name: 'a drop of water' },
        ],
        oddOnes: [3, 4],
        why: 'Living things grow, eat and breathe. Rocks and water do not — two odd ones here.',
      },
      {
        kind: 'cleanSet',
        id: 'c3',
        label: 'Things that are round',
        options: [
          { emoji: '⚽', name: 'a ball' },
          { emoji: '🌕', name: 'the moon' },
          { emoji: '🍊', name: 'an orange' },
          { emoji: '🥕', name: 'a carrot' },
          { emoji: '🧊', name: 'an ice cube' },
        ],
        oddOnes: [3, 4],
        why: 'A carrot is pointy and an ice cube has corners. Round means round all the way.',
      },
      {
        kind: 'fixLabel',
        id: 'f6',
        emoji: '🦔',
        badLabel: 'a hairbrush',
        question: 'This one is tricky. Which label is true?',
        options: ['A hairbrush', 'A hedgehog', 'A pinecone', 'A cactus'],
        answer: 'A hedgehog',
        why: 'It only looks like a brush. Careful trainers check twice before they label a picture.',
      },
    ],
  },
]
